[package]
name = "flip_cards"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rui = { path = "../../." }
rust_search = "2.0.0"